### ISSUE TITLE
Unable to build on macOS

### ISSUE THREAD

**Issue by jserv** [pokemium/Worldwide#47]
I can not build this package on macOS Catalina.
```shell
make osx
```

The error message:
> ld: warning: ignoring file /var/folders/f6/hntbqtjx31lflw_4hxp6kjs80000gn/T/go-link-125565020/000000.o, building for macOS-x86_64 but attempting to link with file built for unknown-unsupported file format ( 0x64 0x86 0x01 0x00 0x00 0x00 0x00 0x00 0xB8 0x11 0x00 0x00 0x01 0x00 0x00 0x00 )

```
$ go version
go version go1.15.3 darwin/amd64
```

**Comment by pokemium** [comment]
Thank you for your issue.
I'm sorry if I'm not good at English.
Build had failed really? It seems that this message is not error but warning. When building on my own Mac(macOS Catalina), I always saw this warning, but build succeeded.

**Comment by jserv** [comment]
I was confused at the warning message generated by ld. There is certainly a file `worldwide.app` built, and it can load Super Mario Land game for me. Thanks for the great work.
